-- Classe A/B/C de chaque modèle, relevée sur le PDM en jeu.
UPDATE catalogue SET classe = 'A' WHERE nom = '811';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Weevil';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Brioso 300';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Club';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Blista Kanjo';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Asbo';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Issi Classic';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Rhapsody';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Panto';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Prairie';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Dilettante';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Blista';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Postlude';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Kanjo SJ';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Previon';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Zion';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Sentinel XS';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Sentinel';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Oracle';
UPDATE catalogue SET classe = 'B' WHERE nom = 'FR36';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Zion Cabrio';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Oracle XS';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Jackal';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Felon GT';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Felon';
UPDATE catalogue SET classe = 'B' WHERE nom = 'F620';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Exemplar';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Windsor Drop';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Cognoscenti Cabrio';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Powersurge';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Sanchez';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Zombie Bobber';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Wolfsbane';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Vortex';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Vindicator';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Vader';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Ruffian';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Rat Bike';
UPDATE catalogue SET classe = 'C' WHERE nom = 'PCJ 600';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Nemesis';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Manchez';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Gargoyle';
UPDATE catalogue SET classe = 'C' WHERE nom = 'FCR 1000';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Faggio Sport';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Faggio';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Esskey';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Enduro';
UPDATE catalogue SET classe = 'C' WHERE nom = 'BF400';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Reever';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Zombie Chopper';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Thrust';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Sovereign';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Hexer';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Hakuchou';
UPDATE catalogue SET classe = 'B' WHERE nom = 'FCR 1000 Custom';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Double-T';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Diabolus';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Defiler';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Daemon';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Cliffhanger';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Bagger';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Avarus';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Akuma';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Shinobi';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Stryder';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Nightblade';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Lectro';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Innovation';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Hakuchou Drag';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Diabolus Custom';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Chimera';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Carbon RS';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Bati 801';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Sanctus';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Clique Wagon';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Manana Custom';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Beater Dukes';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Vamos';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Impaler';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Faction Custom';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Vigero';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Buccaneer';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Yosemite';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Voodoo';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Virgo Classic Custom';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Virgo Classic';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Virgo';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Stallion';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Slamvan';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Sabre Turbo';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Ruiner';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Picador';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Moonbeam Custom';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Moonbeam';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Faction';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Dukes';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Chino';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Blade';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Brigham';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Buffalo EVX';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Ruiner ZZ-8';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Greenwood';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Buffalo STX';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Dominator GTT';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Dominator ASP';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Gauntlet Classic Custom';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Drift Yosemite';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Peyote Gasser';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Gauntlet Hellfire';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Gauntlet Classic';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Deviant';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Tulip';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Clique';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Ellie';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Sabre Turbo Custom';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Gauntlet';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Hustler';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Voodoo Custom';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Tampa';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Pisswasser Dominator';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Phoenix';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Nightshade';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Lurcher';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Faction Custom Donk';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Dominator';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Chino Custom';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Buccaneer Custom';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Vigero ZX';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Dominator GTX';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Hermes';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Coquette BlackFin';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Walton L35';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Yosemite Rancher';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Hellion';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Street Blazer';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Rebel';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Rancher XL';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Kalahari';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Bodhi';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Blazer';
UPDATE catalogue SET classe = 'B' WHERE nom = 'MonstroCiti';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Outlaw';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Caracara 4x4';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Sandking SWB';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Sandking XL';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Merryweather Mesa';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Everon';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Vagrant';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Warrener HKR';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Glendale Custom';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Washington';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Warrener';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Surge';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Stratum';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Stanier';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Schafter';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Regina';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Primo Custom';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Primo';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Premier';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Intruder';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Ingot';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Glendale';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Emperor';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Asterope';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Asea';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Rhinehart';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Cinquemila';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Tailgater S';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Romero Hearse';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Tailgater';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Fugitive';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Stafford';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Super Diamond';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Stretch';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Cognoscenti 55';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Cognoscenti';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Sentinel Classic Widebody';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Sultan RS Classic';
UPDATE catalogue SET classe = 'C' WHERE nom = 'ZR350';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Remus';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Futo GTX';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Calico GTF';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Penumbra FF';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Sultan Classic';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Sentinel Classic';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Sultan';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Kuruma';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Blista Compact';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Cypher';
UPDATE catalogue SET classe = 'B' WHERE nom = 'RT3000';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Euros';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Sugoi';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Komoda';
UPDATE catalogue SET classe = 'B' WHERE nom = '8F Drafter';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Jester Classic';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Flash GT';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Surano';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Comet';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Raiden';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Tropos Rallye';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Schwartzer';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Schafter V12';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Schafter LWB';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Rapid GT Cabrio';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Rapid GT';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Penumbra';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Fusilade';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Feltzer';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Elegy RH8';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Buffalo S';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Buffalo';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Itali GTO Stinger TT';
UPDATE catalogue SET classe = 'A' WHERE nom = '10F Widebody';
UPDATE catalogue SET classe = 'A' WHERE nom = '10F';
UPDATE catalogue SET classe = 'A' WHERE nom = 'SM722';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Corsita';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Comet S2 Cabrio';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Jester RR';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Growler';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Vectre';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Comet S2';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Itali RSX';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Coquette D10';
UPDATE catalogue SET classe = 'A' WHERE nom = 'V-STR';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Imorgon';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Jugular';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Locust';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Neo';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Paragon R';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Schlagen GT';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Itali GTO';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Alpha';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Comet SR';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Neon';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Pariah';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Verlierer';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Specter';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Seven-70';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Ruston';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Massacro';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Khamelion';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Jester';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Futo';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Furore GT';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Coquette';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Carbonizzare';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Bestia GTS';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Banshee';
UPDATE catalogue SET classe = 'A' WHERE nom = '9F Cabrio';
UPDATE catalogue SET classe = 'A' WHERE nom = '9F';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Retinue Mk II';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Dynasty';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Zion Classic';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Nebula Turbo';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Michelli GT';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Cheburek';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Fagaloa';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Retinue';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Tornado';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Manana';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Peyote Custom';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Rapid GT Classic';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Tornado Custom';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Tornado Cabrio';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Pigalle';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Peyote';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Swinger';
UPDATE catalogue SET classe = 'A' WHERE nom = '190z';
UPDATE catalogue SET classe = 'A' WHERE nom = 'GT500';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Torero';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Cheetah Classic';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Z-Type';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Turismo Classic';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Stinger GT';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Stinger';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Roosevelt Valor';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Roosevelt';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Monroe';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Mamba';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Infernus Classic';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Coquette Classic';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Casco';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Sultan RS';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Torero XO';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Zeno';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Ignus';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Tigon';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Furia';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Zorrusso';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Krieger';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Emerus';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Thrax';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Deveste Eight';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Tyrant';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Tezeract';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Taipan';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Entity XXR';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Banshee 900R';
UPDATE catalogue SET classe = 'A' WHERE nom = 'SC1';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Autarch';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Cyclone';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Visione';
UPDATE catalogue SET classe = 'A' WHERE nom = 'XA-21';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Vagner';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Zentorno';
UPDATE catalogue SET classe = 'A' WHERE nom = 'X80 Proto';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Voltic';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Vacca';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Turismo R';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Tempesta';
UPDATE catalogue SET classe = 'A' WHERE nom = 'T20';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Reaper';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Penetrator';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Osiris';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Nero Custom';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Nero';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Itali GTB Custom';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Itali GTB';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Infernus';
UPDATE catalogue SET classe = 'A' WHERE nom = 'GP1';
UPDATE catalogue SET classe = 'A' WHERE nom = 'FMJ';
UPDATE catalogue SET classe = 'A' WHERE nom = 'ETR1';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Entity XF';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Cheetah';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Bullet';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Adder';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Seminole Frontier';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Serrano';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Habanero';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Seminole';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Mesa';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Landstalker';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Bobcat XL';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Bison';
UPDATE catalogue SET classe = 'B' WHERE nom = 'I-Wagen';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Baller ST';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Astron';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Landstalker XL';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Novak';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Toros';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Patriot';
UPDATE catalogue SET classe = 'B' WHERE nom = 'FQ2';
UPDATE catalogue SET classe = 'B' WHERE nom = 'BeeJay XL';
UPDATE catalogue SET classe = 'B' WHERE nom = 'XLS';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Rocoto';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Radius';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Huntley S';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Gresley';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Granger';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Contender';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Cavalcade';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Baller (Old)';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Rebla GTS';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Patriot Stretch';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Dubsta 2';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Dubsta';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Baller LE LWB';
UPDATE catalogue SET classe = 'A' WHERE nom = 'Baller LE';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Bugstars Burrito';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Youga Classic';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Youga';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Surfer';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Speedo';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Rumpo';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Pony';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Paradise';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Minivan Custom';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Minivan';
UPDATE catalogue SET classe = 'C' WHERE nom = 'Burrito';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Youga Classic 4x4';
UPDATE catalogue SET classe = 'B' WHERE nom = 'Rumpo Custom';
